[project]
name = "realtime-camera-filter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "opencv-python>=4.12.0.88",
    "pyfakewebcam>=0.1.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
